name: RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set random password
        run: |
          $pass = "User@" + (Get-Random -Minimum 10000 -Maximum 99999)
          echo "PASSWORD=$pass" >> $env:GITHUB_ENV

      - name: Download & Setup ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -Force
          Copy-Item ".\ngrok-stable-windows-amd64\ngrok.exe" -Destination ".\ngrok.exe"
          dir
          .\ngrok.exe authtoken $env:NGROK_AUTH_TOKEN

      - name: Enable RDP
        run: |
          net user runneradmin $env:PASSWORD
          net localgroup administrators runneradmin /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start ngrok
        run: |
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389"

      - name: Show Info
        run: |
          Start-Sleep -Seconds 10
          Invoke-RestMethod http://127.0.0.1:4040/api/tunnels | ConvertTo-Json
          $tunnel = (Invoke-RestMethod http://127.0.0.1:4040/api/tunnels).tunnels[0].public_url

          echo "===================="
          echo "RDP LOGIN"
          echo "Address: $tunnel"
          echo "User: runneradmin"
          echo "Pass: $env:PASSWORD"
          echo "===================="

      - name: Keep Alive
        run: |
          while ($true) {
            Start-Sleep -Seconds 300
          }
