- name: Download ngrok
  run: |
    Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    Expand-Archive ngrok.zip -Force

    $ngrokPath = ".\ngrok-stable-windows-amd64\ngrok.exe"
    dir

    & $ngrokPath authtoken $env:NGROK_AUTH_TOKEN
